import * as XLSX from "xlsx";
import { FIXED_COLUMN_POSITIONS, SPECIAL_HEADER_MAPPINGS } from "@/lib/types";
import type { ExcelColumnMapping } from "@/lib/types";

export interface ParsedExcelData {
  headers: string[];
  rows: Record<string, string>[];
  mappings: ExcelColumnMapping[];
}

/**
 * Parse an Excel file and auto-map columns to student fields.
 *
 * Mapping strategy:
 *  - Columns A–G (index 0–6): ALWAYS mapped to fixed DB fields by POSITION,
 *    regardless of the header text. This handles variations like
 *    "Họ Tên" vs "Họ tên", "SĐT/ Zalo liên hệ" vs "SĐT/Zalo", etc.
 *  - Columns H+ (index 7+): checked against SPECIAL_HEADER_MAPPINGS by header
 *    text. If matched → fixed field. Otherwise → dynamic_data.
 *  - Columns with header starting with "__EMPTY" (auto-generated by XLSX for
 *    blank headers) are stripped out entirely.
 */
export function parseExcelFile(file: File): Promise<ParsedExcelData> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target?.result as ArrayBuffer);
        const workbook = XLSX.read(data, { type: "array" });
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];

        // Convert to JSON with header row
        const jsonData = XLSX.utils.sheet_to_json<Record<string, string>>(worksheet, {
          defval: "",
          raw: false,
        });

        if (jsonData.length === 0) {
          reject(new Error("File Excel không có dữ liệu"));
          return;
        }

        // allHeaders preserves the original column order (A, B, C, ...)
        const allHeaders = Object.keys(jsonData[0]);

        // Filter out __EMPTY columns (blank headers auto-generated by XLSX)
        const validHeaders = allHeaders.filter((h) => !h.startsWith("__EMPTY"));

        // Build mappings based on POSITION for A-G, then HEADER NAME for H+
        const mappings: ExcelColumnMapping[] = validHeaders.map((header) => {
          const originalIndex = allHeaders.indexOf(header);

          // Columns A-G (index 0–6): fixed by position
          if (originalIndex <= 6) {
            const dbField = FIXED_COLUMN_POSITIONS[originalIndex] ?? null;
            return {
              columnIndex: originalIndex,
              excelHeader: header,
              dbField,
              isFixed: dbField !== null,
            };
          }

          // Columns H+ (index 7+): check special header mappings
          const trimmedHeader = header.trim();
          const specialField = SPECIAL_HEADER_MAPPINGS[trimmedHeader] ?? null;
          return {
            columnIndex: originalIndex,
            excelHeader: header,
            dbField: specialField,
            isFixed: specialField !== null,
          };
        });

        // Build filtered rows (only valid headers, no __EMPTY columns)
        const filteredRows = jsonData.map((row) => {
          const filtered: Record<string, string> = {};
          validHeaders.forEach((h) => {
            filtered[h] = row[h] ?? "";
          });
          return filtered;
        });

        resolve({
          headers: validHeaders,
          rows: filteredRows,
          mappings,
        });
      } catch {
        reject(new Error("Không thể đọc file Excel. Vui lòng kiểm tra định dạng file."));
      }
    };

    reader.onerror = () => reject(new Error("Lỗi đọc file"));
    reader.readAsArrayBuffer(file);
  });
}

/**
 * Convert parsed row to student insert/update data using the column mappings.
 */
export function rowToStudentData(
  row: Record<string, string>,
  mappings: ExcelColumnMapping[]
) {
  const fixedData: Record<string, string> = {};
  const dynamicData: Record<string, string> = {};

  mappings.forEach((mapping) => {
    const value = row[mapping.excelHeader]?.toString().trim() ?? "";
    if (!value) return;

    if (mapping.isFixed && mapping.dbField) {
      fixedData[mapping.dbField] = value;
    } else if (!mapping.isFixed) {
      dynamicData[mapping.excelHeader] = value;
    }
  });

  return { fixedData, dynamicData };
}
